project_name: AD2C

builds:
  - # Build macOS, Linux and Windows versions
    dir: .
    main: ./main.go
    binary: ad2c
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    targets:
      - linux_amd64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - # Replacements for GOOS and GOARCH in the archive name.
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    # Additional files/template/globs you want to add to the archive.
    files:
      - LICENSE
      - README.md
      - templates/*.tpl