
/*
Automatically generated by AD2C (Apple Devices to Code)
https://github.com/jtorvald/AD2C
*/

function getReadableDeviceModel(model) {
    switch(model){ {{range $identifier, $description := . }}
        case "{{$identifier}}": return "{{$description}}"{{end}}
    }
    return "Unknown"
}