
/*
Automatically generated by AD2C (Apple Devices to Code)
https://github.com/jtorvald/AD2C
*/

function getReadableDeviceModel(model) {
    switch(model){ {{range . }}
        case "{{.Identifier}}": return "{{.Description}}"{{end}}
    }
    return "Unknown"
}