name: Build Go
on:
  release:
    types: [published]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v1
        with:
          go-version: 1.19

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release -f .github/.goreleaser.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
